name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    env: 
      SKIP_PREFLIGHT_CHECK: true
      MONGO_URI: ${{ secrets.MONGO_URI }} 
      TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
      PORT: ${{secrets.PORT}}
      SECRET: ${{secrets.SECRET}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install && cd client && npm install
      - name: lint
        run: npm run lint:all
      - name: build
        run: npm run build:client
      - name: test
        run: npm run test:all
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push'  && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstack-open-part11-bloglist" 
          heroku_email: "l0ve2cr3ate@gmail.com"
          procfile: "web: npm start"
          healthcheck: "https://fullstack-open-part11-bloglist.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGO_URI: ${{ secrets.MONGO_URI }} 
          HD_SECRET: ${{secrets.SECRET}}
          HD_SKIP_PREFLIGHT_CHECK: true
        
        
     
     